apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-registry-secret
  namespace: ucebnice-production
spec:
  encryptedData:
    .dockerconfigjson: AgC7bVECckDNT+HBxj+sfUa/vPilIKNFqa7EnfhO2J0qrtEK/qNMT+MIrrQlZvktUZ5K1kY2SVt/B77VGX0cvpTbfCa8d1rL9ODOi83qblcpKCa+zMQCDZYNJbW7I5GkzTCZerfYheWMS3nPXkm9bBR9g3KLjDOXAnRZ815/BrSRF2pQbd6axXhpfEorcks7aAvy3ORn5PfnhFekvZRnGGmhxO8gMNt4rld4Wu/bYFQp9vxg59yLKiWxPbZYAed5Y1RdgXS0KL/PdY3jfhT6MRQE0QFgh4E7t2nDyjgfa4zXxrGnm/u9X2RhYPWXaUjBUs6DiqvxlHaJrFKZi9u3vzO7qo5N3NVmIoAYMdY6CtC7d8UCW4YXVb9iQeyafoIwRsvZOSHsblXmvhIRUMflzBo5uHcoFViMYgRC0ZV70seHHn5fIhTNYiWfAwCPPDWwOpsy2vBo/fvU8mSaCSvqs2uFFBjtpIzKj+Gu0YC4+xli8nT8vDvQ03KEVJxZeLE0oVYFaaaKRBPdbBoA5BvB5zpN5E+yCjSoMZGEHN3lmomQuPNJnEtm7mZHL+EsZrf9A0nJFxqBPWhuXXjr8BYfoxU1BG/99IsEeAoCyM5nAcYH5B7oOUX+qj0yDq/wv0PB1jw3/byxCCsqHqB4tnPXYhyXGxc3vY4Yzgz2i+ssnwWC+1Gtb+zTVDMgjsC+S0AcDQcr3SEg29yPrpWyiJG2Y3xRFNex7m0ANwTLGDb+9NowKiMBlwDkc294qf5ffgOI7V6UY/rCrzhYwDiAsFwoq+Vj8zLn2JevTIXnX8qppSMi8gHnVr1YIG7cloab1oqQnGtSf5M0aCJmkAk8nHmGsWNiJWG3bkcMLCe9fVnBQL1EQfKuLc9xyKeB/ncX5aPNAP8Rx0cc4agFsKefoR2EZQOzdhT9/bJ40XhZwAL2gfmppRY5WU/8xP/pCea/kmKZsoraDifRtSCruBa+fVHzldqWZKRTq0w4Lo/51ZE3yWNO+VTj7Q==
  template:
    metadata:
      creationTimestamp: null
      name: harbor-registry-secret
      namespace: ucebnice-production
    type: kubernetes.io/dockerconfigjson
---
