apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ucebnice-production-postgres-secret
  namespace: ucebnice-production
spec:
  encryptedData:
    password: AgCjCQVjIuZpwyz9sYmriAtgCkJ4N7r+lQ90tmdpUXIqtYiYG2GgB+ligb4y2sNjZH8L22ut+0lxQwD4pTLYUGc4DBrkiR5LgsST6lPZ/c4s+yFkFESspkSN75xIdfCULgOr6uqr5tjFdt3j2APOmgc1MO2TlMJPxd/7eVZBe3+kzyPaUUFfUoGrAFf5ft2r1Z8IaraHAeuD4qE9re/XklWwvpujXxErAsH1LH/tofWinqvagf8ZfuNyWu9kpsfhstgYO+b3E7GHwht9I3pNlxeNa97aXHNXn5hps1638izNePRBim8/2sWuWBrSmeeCB/x5dzvQWPSVby2P7hu4VfpbOJDT2f7EqWoud83fGFaLnd1R2Ap7amKhA/aVzoBs68ESud7qSpd/RswTlp/DWRkz889118tnwJ5MH1dkhi4HSeHekwTWfqjZS8mVJkrzSpez2OPQGanTEnzpbGWrCoNeVqCkMAhbONvvquE25AXgiMinq45KkD+7yvt4DfcyS0DTyuil4LmmNLKv2QItfbHomqcGC8Uyvzb42ktMPezVi17TBMRTmmv9IYUlyYH3N6HDZRhwFJwKDbGMQwYdkuqkw+LwuQzCNu8v91ybJH7VoTRRtF0K6B/qOdEKqJCtj/pemiTuYUrsZFJg14/tUzlFCRkSY3C13B67L4pbzwjTiSSSm7nBg34AgBdO2dH9ZnbenfW+LmidQZTJffd6cRmPCa0l/b1lYBRh4X/I9K+L0vPLA/1GZ37+Whgz8w==
    username: AgAEh1UNrcrQmdTlXPV0O5v734dFbUAYTwKMb1juloHkk3F6+2v+HhepFoRdmfkaPrX7j+sMZZx2d2oJRAvCiDPWd2QC5GvfoB0322HrUOcsQRRzMjOH9LhvD6U50xBu5XFmrYeJD4vkK8RRRc9Dt3rq8WrIva9xt7yy38GICEy+FjOI5glJrcCYZ9h+1vDKci1XKjDLJkVyq8r9Ip+370Lt78BypgjJ8F5+VyrwLFAXcUU0fPGq9uu9woyoRdt5dAAC9tUBRHZT9Ve3TlRvb55DmPkLIhI7xXWNYTfW2pnKr3LyEh8djUSEnGDJNs6tsJ7RLaaOc8dm06w5yfRsDVV+FDt9EgLjh8QV3ZHkhyA1NqvOBrmTGHL90G18XUTLnwAOfA68Gq8Pl6Zak9siGnWKmLVomQbtFUKbIYYfRIVGmjF2OwJHEFVQUPBWuKC4IT5FwCHIjDbl9+xviiwEi5rSgzNYP/oG5nmyZb2jFXYDpRqxU+/i+UXVvAlkyo8Fj1uwmPl7ZSjjvAx/St/JZY12PmEQz3JaMUKH/AMLvpFdF1P+kXZ44CyQM2FmCvPDH+pDczZrK/8jpL2ZaS5HIi+Qks4MKKCTpVKjXQe089vKJ4kaO7ZJisoRrkz1QIE/Nls8Z6RnBcyMS+esDAhMmO0afq3vLhDzJ8yj7t4XxVo7ZAyHKP1UR68lSFECE3lUyP3f1/jum4ROeA==
  template:
    metadata:
      creationTimestamp: null
      name: ucebnice-production-postgres-secret
      namespace: ucebnice-production
---
